export class Taulia {
    curentInvoice: any;
    curentInvoiceTrnDtl: any;
    generateEdiPopup: boolean = false;
    ediErrorLogPopup: boolean = false;
    invoice_mst_pk: number;
    invoice_number: string;
    roe: number;
    pol_pk: number = 0;
    pod_pk: number = 0;
    created_by_fk: number = 0;

    headerData: HeaderData;
    containerDetail: ContainerDetail[];
    chargesData: ChargesData;
    fileName: any;
    filePath: any;
    errorLogDetails: any;
}


export class HeaderData {
      isA_AUTHOR_INFO: string;
      isA_AUTHOR_INFO_VAL: string;
      isA_SECURITY_INFO: string;
      isA_SECURITY_INFO_VAL: string;
      coL_ZZ_11: string;
      isA_SENDER_ID: string;
      coL_ZZ_12: string;
      isA_RECEIVER_ID: string;
      edI_CREATED_DATE: string;
      edI_CREATED_TIME: string;
      uS_EDI: string;
      edI_VERSION: string;
      isA_CONTROL_NUMBER: string;
      acK_REQUEST: string;
      usagE_INDICATOR: string;
      gS_SENDER_CODE: string;
      gS_RECEIVER_CODE: string;
      edI_CREATED_DATE_1: string;
      edI_CREATED_TIME_1: string;
      grouP_CONTROL_NUMBER: string;
      gS_RES_AGENCY_CODE: string;
      gS_VERSION: string;
      sT_INVOICE_FLAG: string;
      sT_TRANS_CRTL_NO: string;
      invoicE_DATE: string;
      invoicE_NO: string;
      purchasE_ORDER_DATE: string;
      purchasE_ORDER_NO: string;
      releasE_NO: string;
      changE_ORDER_SEQ_NO: string;
      biG_TRANS_TYPE_CODE: string;
      cuR_ENTITY_IDENTI_CODE: string;
      invoicE_CURRENCY_CODE: string;
      inV_ROE: string;
      reF_43: string;
      supporT_DOC_NO: string;
      reF_IA: string;
      internaL_VENDOR_NO: string;
      reF_IT: string;
      internaL_CUSTOMER_NO: string;
      reF_E9: string;
      attachmenT_TYPE: string;
      n1_RE: string;
      partY_TO_RECEIVE: string;
      receiveR_ADDRESS: string;
      receiveR_CITY_NAME: string;
      statE_PROVINCE_CODE: string;
      receiveR_POST_CODE: string;
      receiveR__COUNTRY_CODE: string;
      terM_TYPE_CODE: string;
      terM_BASIS_DT_CODE: string;
      terM_DISCOUNT_PERCENT: string;
      terM_DISCOUNT_DUE_DT: string;
      terM_DISCOUNT_DAYS_DUE: string;
      termS_NET_DUE_DT: string;
      terM_NET_DAYS: string;
      terM_DISCOUNT_AMT: string;
      terM_DEFFER_DUE_DT: string;
      deffeR_AMOUNT_DUE: string;
      percenT_INVOICE_PAYABLE: string;
      invoicE_REMARKS: string;
      dtM_VALIDITY_DATE: string;
      datE_TIME_QUALIFIER: string;
}

export class ContainerDetail {
    assigN_IDENTIFICATION: string;
    qualitY_INVOICED: string;
    units: string;
    uniT_PRICE: string;
    uniT_PRICE_CODE: string;
    servicE_RENDER: string;
    containeR_NO: string;
    iT1_KK: string;
    containeR_TYPE: string;
    taX_TYPE_CODE: string;
    txI_MONETARY_AMOUNT: string;
    txI_PERCENT: string;
    clasS_TRADE_CODE: string;
    neT_ITEM_PRICE: string;
    ctP_UNIT_PRICE: string;
    ctP_QUANTITY: string;
    compositE_UNIT: string;
    ctP_PRICE_MULTI_QUALIFIER: string;
    ctP_MULTIPLIER: string;
    ctP_MONETARY_AMOUNT: string;
    piD_FREE_FORM: string;
    piD_PRODUCE_CHARACTER: string;
    piD_AGENCY_CODE: string;
    piD_DESCR_CODE: string;
    containeR_DESCRIPTION: string;
    actuaL_DATE: string;
    starT_DATE: string;
    enD_DATE: string;
    vesseL_CODE: string;
    vesseL_NAME: string;
    vesseL_COUNTRY_CODE: string;
    voyagE_NO: string;
    stD_CARRIER_ALPHA_CODE: string;
    vesseL_REQUIREMENT_CODE: string;
    vesseL_TYPE_CODE: string;
    vesseL_CODE_QUALIFIER: string;
    r4_ACTIVITY_LOCATION: string;
    r4_UN_CODE: string;
    r4_PORT_ID: string;
    r4_PORT_NAME: string;
    r4_COUNTRY_CODE: string;
    r4_TERMINAL_ID: string;
};

export class ChargesData {
  tdS_AMOUNT1: string;
  tdS_AMOUNT2: string;
  nO_OF_CONTAINERS: string;
  nO_OF_SEGMENT: string;
  traN_SET_CNTRL_NO: string;
  gE_NO_OF_TRANS_SET: string;
  gE_GROUP_CONTROL_NUMBER: string;
  ieA_NO_OF_INCLUDE_FN: string;
  ieA_INTER_CHNG_CTRL_NO: string;
}
