export const ConfigSetup = {
    // DECIMAL_SEPARATOR: ',',
    // THOUSANDS_SEPARATOR: '.',
    // MIN_FRACTIONDIGITS: 2,
    // MAX_FRACTIONDIGITS: 2,
    // DATEFORMAT: 'YYYY-MM-DDTHH:mm:ss',
    // DEFAULT_LOCALE: 'en-US',
    // LOCALE: 'es-PY',
    // LANGUAGE_CODE: 'es',
    USER_LANGUAGES: [{
        ID: 1,
        LOCALE: 'en-US',
        LANGUAGE_CODE: 'en',
        NAME: 'English US',
        DATE_FORMAT: 'dd LLL| HH:mm',
        VCS_DATE_FORMAT: 'MM/dd/yyyy',
        DATE_PLACEHOLDER: 'MM/DD/YYYY',
        UTC_OFFSET: '+05:30',
        // UTC_OFFSET: '-08:00',
        THOUSANDS_SEPARATOR: ',',
        DECIMAL_SEPARATOR: '.',
        MAX_FRACTIONDIGITS: 2,
        MIN_FRACTIONDIGITS: 2,
        DATE_INPUT_FORMAT: 'YYYY-MM-DDTHH:mm:ss',
    }, {
        ID: 2,
        LOCALE: 'en-UK',
        LANGUAGE_CODE: 'en',
        NAME: 'English United Kingdom',
        DATE_FORMAT: 'dd LLL| HH:mm',
        VCS_DATE_FORMAT: 'MM/dd/yyyy',
        DATE_PLACEHOLDER: 'MM/DD/YYYY',
        UTC_OFFSET: '+05:30',
        // UTC_OFFSET: '-08:00',
        THOUSANDS_SEPARATOR: ',',
        DECIMAL_SEPARATOR: '.',
        MAX_FRACTIONDIGITS: 2,
        MIN_FRACTIONDIGITS: 2,
        DATE_INPUT_FORMAT: 'YYYY-MM-DDTHH:mm:ss',
    }, {
        ID: 3,
        LOCALE: 'es-PY',
        LANGUAGE_CODE: 'es', 
        NAME: 'Spanish - Paraguay',
        DATE_FORMAT: 'dd LLL | HH:mm',
        VCS_DATE_FORMAT: 'dd/MM/yyyy',
        DATE_PLACEHOLDER: 'DD/MM/YYYY',
        UTC_OFFSET: '+05:30',
        // UTC_OFFSET: '-08:00',
        THOUSANDS_SEPARATOR: '.',
        DECIMAL_SEPARATOR: ',',
        MAX_FRACTIONDIGITS: 2,
        MIN_FRACTIONDIGITS: 2,
        DATE_INPUT_FORMAT: 'YYYY-MM-DDTHH:mm:ss',
    }, {
        ID: 4,
        LOCALE: 'pt-BR',
        LANGUAGE_CODE: 'es',
        NAME: 'Spanish - Paraguay',
        DATE_FORMAT: 'dd LLL | HH:mm',
        VCS_DATE_FORMAT: 'dd/MM/yyyy',
        DATE_PLACEHOLDER: 'DD/MM/YYYY',
        UTC_OFFSET: '+05:30',
        // UTC_OFFSET: '-08:00',
        THOUSANDS_SEPARATOR: '.',
        DECIMAL_SEPARATOR: ',',
        MAX_FRACTIONDIGITS: 2,
        MIN_FRACTIONDIGITS: 2,
        DATE_INPUT_FORMAT: 'YYYY-MM-DDTHH:mm:ss',
    }],

}
