export const ERRMSG = {
    GFS000001: 'All data saved successfully.',
    GFS000002: 'Userid has been Locked.',
    GFS000003: 'Logged in Successfully.',
    GFS000004: 'Your password has expired.',
    GFS000005: 'Your password Changed Successfully.',
    GFS000006: 'Record deleted successfully.',
    GFS000007: 'Record deactivated successfully',
    GFS000008: 'Record activated successfully',
    GFE000050: 'Service is used in downstream Process',
    GFS000010: 'Record updated successfully.',
    GFS000011: 'User is an Approver',
    GFS000012: 'User is not authorized to approve.',
    GFS000013: 'WorkFlow not defined',
    GFS000016: 'Record deleted successfully.',
    GFE000018: 'Existing and New password cannot be same',
    GFE000019: 'User does not exists',
    GFE000020: 'Existing password is wrong',
    GFE000021: 'New password should not match with last 3 password',
    GFE000022: 'Password changed successfully',
    GFE000023: 'Invalid OTP',

    GFE000001: 'Internal Server Error.',
    GFE000002: 'Duplicate Code.',
    GFE000003: 'Invalid object.',
    GFE000004: 'Incorrect Login Credentials.',
    GFE000005: 'Invalid User Details.',
    GFE000006: 'InCorrect Old Password.',
    GFE000007: 'Password cannot be same as the last 3 passwords.',
    GFE000008: 'Week Password.',
    GFE000009: 'This user ID is already assigned.',
    GFE000010: 'Data is not saved due to some errors.',
    GFE000011: 'Record already deleted by other user.',
    GFE000012: 'The Record is modified by some other user.',
    GFE000013: 'There was an exception in fetching the data.',
    GFE000014: 'One of the argument is null in the Query.',
    GFE000015: 'One of the argument is null in the Query.',
    GFE000016: 'The record cannot be deleted as it is used in downstreams.',
    GFE000017: 'Invalid Excel File.There is a mismatch in columns.',
    GFE000027: 'Valid Quotation exists for selected customer',
    GFE000077: 'Valid Spot Rate exists for selected customer',
    // GFE000031: 'Amend the booking Quantity or override the booking Quantity as per excel',
    GFE000031: 'override booking quantity as per excel',
    // Global
    GFE23503: 'You can only de-activate as there has been transactions for this Record.',
    GFE23505: 'Record already Available.',
    GFE23506: 'No records found with the selected combination',
    GFE000036: 'Requested data is not available!',
    GFE000037: 'Apporved details are mandatory!',
    GFE000038: 'Can not edit for approved policy!',
    GFE000039: 'Cant edit for rejected policy',
    GFE000045: 'You have already liked this announcement',
    GFE000046: 'You have already dis-liked this announcement',
    // Global End

    // Warning Message Section
    GFMO0000017: 'Are you sure you want to edit the number of convoys?',
    GFW000001: 'Are you sure you want to De-activate this record?',
    GFW000002: 'Are you sure you want to delete this record?',
    GFW000003: 'Are you sure you want to cancel the changes?',
    GFW000004: 'Please fill all mandatory fields',
    GFW000005: 'Are you sure you want to Activate this record?',
    GFW000006: 'You have attempted to activate an advanced opening of an operational schedule.<br/><br/><br/> Do you wish to proceed?',
    GFW000007: '<a class="text-click-here">Click here</a>  to update RDS, PCMM.',
    GFW000008: 'Do You Wish to confirm your booking and exit?',
    GFW000009: 'Your booking has been confirmad with ref nr. <br/> <span class="text-link"> %bookingReferenceNo% .',
    GFW0000010: 'Do you wish to cancel your booking for ref. nr. ',
    GFW0000011: 'Kindly Upload Excel File',
    GFW0000012: 'Data Uploaded successfully',
    GFW0000013: 'Kindly select booking to upload',
    GFW0000014: 'You wish to proceed to accept quotation ref. <br/> <a class="text-link" ><ID></a>',
    GFW0000114: 'You wish to proceed to accept Spot Rate ref. <br/> <a class="text-link" ><ID></a>',
    GFW0000015: 'You wish to proceed to renew quotation ref.  <br/> <a class="text-link"> <ID> </a> which <exp>',
    GFW0000115: 'You wish to proceed to renew Spot Rate ref.  <br/> <a class="text-link"> <ID> </a> which <exp>',
    GFW0000016: 'You wish to proceed to reject quotation ref. <br/> <a class="text-link"><ID></a>',
    GFW0000116: 'You wish to proceed to reject Spot Rate ref. <br/> <a class="text-link"><ID></a>',
    GFW0000017: 'Are you sure you wish to re-nominate booking Ref. Nr. %bookingReferenceNo%? <br/><br/>Once the booking re-nominated your booking the existing booking for the current vessel will be cancelled and to longer available. <br/><br/> Are you sure you wish to proceed?.',
    GFBK0000017: 'Are you sure you wish to change the destination of booking Ref. Nr. %bookingReferenceNo%? <br/><br/>Once the destination is changed your existing booking for the current destination will be cancelled and no longer available. <br/><br/> Are you sure you wish to proceed?.',
    GFW0000018: 'Do you wish to confirm your modification of booking and exit?',
    GFW0000070: 'Do you wish to Approve the Restricted booking and exit?',
    GFW0000019: 'Your booking has been confirmad with ref nr. <br/> <span class="text-link"> %bookingReferenceNo% </span>.',
    GFW0000020: 'Your booking has been confirmad with ref nr. <br/> <span class="text-link"> %bookingReferenceNo% </span>.',
    GFW0000021: 'Your booking has been confirmad with ref nr. <br/> <span class="text-link"> %bookingReferenceNo% </span>.',
    GFW0000022: 'Please provide at least one filter criteria to avoid processing large amount of data',
    GFW0000023: 'You are selecting more than 1 week, which will result in large amount of data to process, do you want to continue?',
    GFW0000024: 'Please select To date',
    GFW0000025: 'Please select From date',
    // Warning message end

    GFM000001: 'Please select From Port',
    GFM000002: 'Please select To Port',
    GFM000003: 'From and To port cannot be same',
    GFM000004: 'No Routes configured for selected port',
    GFM000005: 'Please select ports to generate',
    GFM000006: 'From and To port cannot be same',
    GFM000007: 'Routes already configured for selected port',
    GFM000008: 'Are you sure to delete this record?',
    GFM000009: 'Do you want to de-activate record?',
    GFM000010: 'Kindly select the conditional clause item',
    GFM000011: 'Terminals are not configured for selected port',
    GFM000012: 'To date must be greater than From date',
    GFM000013: 'No schedules available for selected criteria',
    GFM000014: 'Rates are not available for selected criteria',
    GFM000015: 'Kindly select Customer',
    // tslint:disable-next-line: max-line-length
    GFM000016: 'Your Quotation has been saved as <br/><ID> in <status> status. <br/><br/> You may now  <a class="text-link font-weight-semibold" (click)="quotepreview()">Preview</a> or  <a class="text-link  font-weight-semibold" (click)="quoteSend()">Send</a> this quotation or Close',
    GFM000116: 'Your Spot Rate has been saved as <br/><ID> in <status> status. <br/><br/> You may now  <a class="text-link font-weight-semibold" (click)="quotepreview()">Preview</a> or  <a class="text-link  font-weight-semibold" (click)="quoteSend()">Send</a> this Spot Rate or Close',
    GFM000017: 'Port cannot be added as the previous schedule is closed.',
    GFM000018: 'Expiry Alert days must be between 1-30',
    GFM000019: 'File size is Exceded',
    GFM000020: 'Uploaded file is not Valid',
    GFM000021: 'File is not valid',
    GFM000022: 'The quotation ref.<a class="text-link font-weight-semibold" (click)="quotepreview()"><ID></a> has been rejected with following reason',
    GFM000122: 'The Spot Rate ref.<a class="text-link font-weight-semibold" (click)="quotepreview()"><ID></a> has been rejected with following reason',

    GFE000044: 'Sequence Protocol not Exists',
    GFE000047: 'Invalid Customer',
    GFE000048: ' Invalid Voyage Number',
    GFE000049: ' Invalid Freight Type',
    GFE000035: ' Report Name Aready Exists',
    GFE000026: 'Only Admin is autherized user to delete',

    GFE000053: 'Sequence Category already exists in system.',
    GFE000052: 'Customer Name already exists in system',


    // for taulia

    GFS000058: 'Invalid File Format',
    GFE000059: 'MARITIMO" or "ON-CARRIER" Column not present in the Excel sheet.',
    GFE000060: '"B/L" or "BLFLUVIAL" Column not present in the Excel sheet.',
    GFE000061: 'VESSEL_IMO_CODE Column not present in the Excel sheet.',
    GFE000062: '"CNTR" Column not present in the Excel sheet.',
    GFE000063: '"FECHA RENDIDA" Column not present in the Excel sheet.',
    GFE000041: 'File not Uploaded. Please view the Error Log for more details',
    GFE000084: 'Alias Name Already Exist for another User',
    GFE000082: 'Mobile Number Already Exist for another User',
    GFE000083: 'Email Id Already Exist for another User'
    
}
