

export const TableHeader = {
    Status: 'Success',
    StatusCode: 'GFE000001',
    Data: [
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 19,
        columnName: 'col1',
        columnCaption: 'Col1',
        columnTitle: 'Col1/Col1',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '6rem',
        isVisible: true,
        displayOrder: 1,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 20,
        columnName: 'col2',
        columnCaption: 'Col2',
        columnTitle: 'Col2',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '7rem',
        isVisible: true,
        displayOrder: 2,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 23,
        columnName: 'col3',
        columnCaption: 'Col3',
        columnTitle: 'Col3',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '6rem',
        isVisible: true,
        displayOrder: 3,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 24,
        columnName: 'col4',
        columnCaption: 'Col4',
        columnTitle: 'Col4',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '4rem',
        isVisible: true,
        displayOrder: 4,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 25,
        columnName: 'col5',
        columnCaption: 'Col5',
        columnTitle: 'Col5',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '5rem',
        isVisible: true,
        displayOrder: 5,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 26,
        columnName: 'col6',
        columnCaption: 'Col6',
        columnTitle: 'Col6',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '5rem',
        isVisible: true,
        displayOrder: 6,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 28,
        columnName: 'col7',
        columnCaption: 'Col7',
        columnTitle: 'Col7',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '5rem',
        isVisible: true,
        displayOrder: 6,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 29,
        columnName: 'col8',
        columnCaption: 'Col8',
        columnTitle: 'Col8',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '5rem',
        isVisible: true,
        displayOrder: 6,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 30,
        columnName: 'col9',
        columnCaption: 'Col9',
        columnTitle: 'Col9',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '5rem',
        isVisible: true,
        displayOrder: 6,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 31,
        columnName: 'col10',
        columnCaption: 'Col10',
        columnTitle: 'Col10',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '5rem',
        isVisible: true,
        displayOrder: 6,
      },
      {
        gridUserConfigPK: 0,
        formMasterFK: 2,
        userMasterFK: 1,
        fieldConfigFK: 27,
        columnName: 'hiddenField',
        columnCaption: '',
        columnTitle: '',
        controlname: 'ColGrid',
        controltype: 'Grid',
        isEnabled: true,
        isMandatory: false,
        maxLength: 0,
        isDisplayMandatory: false,
        columnAlign: 'left',
        columnWidth: '1rem',
        isVisible: true,
        displayOrder: 7,
      },
    ]
};

export const TableRawData = {
  Status: 'Success',
  StatusCode: 'GFS000001',
  Data: [
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    },
    {
      col1: 'col1',
      col2: 'col2',
      col3: 'col3',
      col4: 'col4',
      col5: 'col5',
      col6: 'col6',
      col7: 'col7',
      col8: 'col8',
      col9: 'col9',
      col10: 'col10',
      col11: 'col11',
      active: 1
    }
  ]
};
export const CostGroupRawData = {
  Status: 'Success',
  StatusCode: 'GFS000001',
  Data: [
    {
      id: 'Stevedoring',
      text: 'Stevedoring',
      value: 'Stevedoring',
      name: 'Stevedoring'
    }, {
      id: 'PortCosts',
      text: 'Port Costs',
      value: 'Port Costs',
      name: 'PortCosts'
    }, {
      id: 'Owners',
      text: 'Owners',
      value: 'Owners',
      name: 'Owners'
    }, {
      id: 'General',
      text: 'General',
      value: 'General',
      name: 'General'
    }
  ]
};

export const CostApplicableRawData = {
  Status: 'Success',
  StatusCode: 'GFS000001',
  Data: [
    {
      id: 'Full',
      text: 'Full',
      value: 'Full',
      name: 'Full'
    }, {
      id: 'Empty',
      text: 'Empty',
      value: 'Empty',
      name: 'Empty'
    }, {
      id: 'Both',
      text: 'Both',
      value: 'Both',
      name: 'Both'
    }
  ]
};

export const CostCostListRawData = {
  Status: 'Success',
  StatusCode: 'GFS000001',
  Data: [
    {
      id: 'Principal',
      text: 'Principal',
      value: 'Principal',
      name: 'Principal'
    }, {
      id: 'Agency',
      text: 'Agency',
      value: 'Agency',
      name: 'Agency'
    }
  ]
};

