export interface ChargeMasterObject {
    userFK: number;
    chargemasterPk: number,
    chargeId: string,
    chargeName: string,
    chargegroupIfk: string,
    chargeGroup: string,
    commoditygroupIfk: string,
    commodityGroup: string,
    incometypeIfk: string,
    incomeType: string,
    chargebasisIfk: string,
    chargebasis: string,
    currencyId: string ,
    currencyfk: string,
    vatIfk: string,
    vat: string,
    commisionable: boolean,
    vatos: boolean,
    advatos: boolean,
    revenueAccount: string,
    chartOfAccount: string,
    chargetypeIfk: string,
    chargetype: string,
    created_by_fk: number,
    last_updated_by_fk: null,
    versionNo: number,
    last_updated_on: string,
    created_on:string,
}

