export interface RblEntryModel {
    childbookingpk: number;
    locationfk: string;
    bookingid: string;
    bookingmasterfk: number;
    bookingdate: string;
    referencetype: string;
    referencefk: string;
    referencenumber: string;
    customerfk: number;
    shipperfk: string;
    consigneefk: string;
    polfk: number;
    polterfk: number;
    polagentfk: string;
    podfk: number;
    podterfk: number;
    podagentfk: string;
    tosfk: number;
    bookingtype: number;
    ladenwgt: number;
    bookingstatus: string;
    mloblnr: string;
    bkgcur: number;
    bkgamt: number;
    is_active: number;
    created_by_fk: number;
    created_on: any;
    last_updated_by_fk: string;
    last_updated_on: any;
    version_no: string;
    commercial_schedule_hdr_fk: number;
    blnumber: number;
    bldate: number;
    blstatus: number;
    priority: string;
    notify_fk: string;
    shippername: string;
    shipperadd: string;
    shipperadd2: string;
    shippercity: string;
    shippercountry: string;
    shipperrucnr: string;
    consgineename: string;
    consigneeadd: string;
    consigneeadd2: string;
    consigneecity: string;
    consigneecountry: string;
    consigneerucnr: string;
    notifyname: string;
    notifyadd: string;
    notifyadd2: string;
    notifycity: string;
    notifycountry: string;
    notifyrucnr: string;
    cntrcnt: string;
    despachodenr: string;
    original_rbl_fk: string;
    original_rbl_doc: string;
    version_remarks: string;
    customercode: string;
    customername: string;
    customerimage: string;
    servicecode: string;
    servicename: string;
    voynr: string;
    poltername: string;
    poleta: string;
    poletd: string;
    podtername: string;
    podeta: string;
    podetd: string;
    blstatusdesc: string;
    regdesalidat: string;
    polname: string;
    podname: string;
    loaddate: string;
    sh_cntry_name: string;
    cn_cntry_name: string;
    np_cntry_name: string;
    sameasconsignee: boolean;
    cntrlist: CntrList[];
    ver_email_app_file: string;
    ver_req_by: string;
    ver_req_designation: string;
    remarksList: any;
    version_exists: number;
    shpmentDtls: shpmentDtls[];
}
export interface CntrList {
    childbkgcontainerpk: number;
    childbookingfk: number;
    childbkgctypefk: number;
    bookingcontainerfk: number;
    shipper: string;
    shipperadd: string;
    consignee: string;
    consigneeadd: string;
    notifyparty: string;
    notifyadd: string;
    mothervessel: string;
    mlo: string;
    mloblnr: string;
    childbkgnr: string;
    containernumber: string;
    containertypefk: number;
    commgrpfk: number;
    commfk: number;
    grossweight: number;
    tareweight: number;
    volume: number;
    imdg: string;
    unnr: string;
    temp: string;
    containerseal: string;
    customsseal: string;
    packtype: string;
    packqty: number;
    marks: string;
    description: string;
    ncmnr: string;
    remarksnumber: string;
    remarks2: string;
    remarks3: string;
    is_active: number;
    created_by_fk: string;
    created_on: string;
    last_updated_by_fk: string;
    last_updated_on: string;
    version_no: string;
    hazmat_approval: number;
    reefer_approval: number;
    nch_file_data: string;
    containersize: string;
    loaded: boolean;
    load_date: string;
    load_print: string;
    discharged: boolean;
    discharge_date: string;
    discharge_print: string;
    dischargetime: string;
    loadtime: string;
    stowpos: string;
    haz_ref_app_date: string;
    shipperadd2: string;
    shippercity: string;
    shippercountry: string;
    shipperrucnr: string;
    consigneeadd2: string;
    consigneecity: string;
    consigneecountry: string;
    consigneerucnr: string;
    notifyadd2: string;
    notifycity: string;
    notifycountry: string;
    notifyrucnr: string;
    is_lcl: number;
    ver_modified_cols: string;
    containertype_id: string;
    cntrtype: string;
    netweight: number;
    commoditygroup_pk: number;
    commoditygroup_id: string;
    commodityname: string;
    commoditygroup_desc: string;
    cntrpref: number;
}
export interface shpmentDtls {
    bookingmasterfk: number;
    podfk: number;
    podname: string;
    podterfk: number;
    podtername: string;
    regdesalidat:string;
    despachodenr: string;
    npList: {
        notifyname: string;
        notifyadd: string;
        notifyadd2: string;
        notifycity: string;
        notifycountry: string;
        notifyrucnr: string;
    }
    conList: 
        {
          consgineename: string,
          consigneeadd: string,
          consigneeadd2: string,
          consigneecity: string,
          consigneecountry: string,
          consigneerucnr: string
        }
    remarksList: 
        {
        rblversionremarkspk: number,
        childbookingfk: number,
        version_remarks: string,
        is_active: number,
        created_by_fk: number,
        created_on: string,
        last_updated_by_fk: number,
        last_updated_on: string,
        version_no: number
        }       
}

